### ISSUE TITLE
Can it work on React Native? 

### ISSUE THREAD

**Issue by ducpt2** [VirgilSecurity/demo-firebase-js#4]
I am wondering that Can it work on React Native? And how to implement?

Thank you.

**Comment by xlwknx** [comment]
Hi @ducpt2 
This demo was intended for browser use, but it can be implemented with React Native.
You need to implement [this](https://github.com/VirgilSecurity/virgil-sdk-javascript/blob/master/src/Storage/KeyEntryStorage/IKeyEntryStorage.ts#L83) interface for your react native platform and use pass it [here](https://github.com/VirgilSecurity/demo-firebase-js/blob/master/src/services/VirgilApi.ts#L17) with second parameter. 
There is Api Reference for PrivateKeyStorage class:
http://virgilsecurity.github.io/virgil-sdk-javascript/classes/privatekeystorage.html

**Comment by paolospag** [comment]
Hi @xlwknx 
I noticed `VirgilApi.ts` file doesn't exist anymore. Is this explanation still valid? How to implement it in React Native today?

I'm a bit confused.

**Comment by xlwknx** [comment]
Hi @paolospag.
No this explanation for older version of the demo. Now it even easier, you don't need to implement your key storage:
Here the instruction:
https://github.com/VirgilSecurity/virgil-e3kit-js#react-native-usage
And here you need to paste it:
https://github.com/VirgilSecurity/demo-firebase-js/blob/master/src/models/UserModel.ts#L41
